# -*- coding: utf-8 -*-
"""Copy of Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNGTHLPFBKfl7wdBdZe8D6IHG4E_xzvn
"""

# ==========================================
# MACHINE LEARNING & DATA SCIENCE ASSIGNMENT
# Dataset: Bank Marketing
# ==========================================

# ==========================================
# 1. Import Libraries
# ==========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ==========================================
# 2. Upload Dataset
# ==========================================

uploaded = files.upload()

df = pd.read_csv("bank.csv")

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

# ==========================================
# QUESTION 1
# Dataset Inspection
# ==========================================
# ==========================================
# QUESTION 1
# Dataset Inspection
# ==========================================

print("First 5 rows:")
display(df.head())

print("\n" + "="*60)
print("Dataset Information:")
print("="*60)

df.info()

print("\n" + "="*60)
print("Descriptive Statistics:")
print("="*60)

display(df.describe())

print("\n" + "="*60)
print("Missing Values:")
print("="*60)

missing_values = df.isnull().sum()
print(missing_values)

print("\nTotal missing values:", missing_values.sum())

# ==========================================
# QUESTION 2
# Linear Regression
# ==========================================

X = df[['age']]
y = df['balance']

# Split data into 70% training and 30% testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

# Create Linear Regression model
linear_model = LinearRegression()

# Train the model
linear_model.fit(X_train, y_train)

# Make predictions
y_pred = linear_model.predict(X_test)

# Calculate MSE
mse = mean_squared_error(y_test, y_pred)

# Calculate R2
r2 = r2_score(y_test, y_pred)

print("\nLinear Regression Results")
print("-" * 40)

print("Mean Squared Error (MSE):", mse)
print("R2 Score:", r2)

# ==========================================
# QUESTION 3
# Mathematical Interpretation
# ==========================================

theta1 = linear_model.coef_[0]
theta0 = linear_model.intercept_

print("Slope (θ1):", theta1)
print("Intercept (θ0):", theta0)

print("\nFinal Linear Equation:")
print(f"ŷ = {theta1:.4f} X + {theta0:.4f}")

# ==========================================
# QUESTION 4
# Logistic Regression
# ==========================================

# Convert target from yes/no to 0/1
df['deposit_binary'] = df['deposit'].map({
    'no': 0,
    'yes': 1
})

# Select two numeric features
X_class = df[['duration', 'balance']]

# Binary target
y_class = df['deposit_binary']

# Split data
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_class,
    y_class,
    test_size=0.30,
    random_state=42,
    stratify=y_class
)

# Create Logistic Regression model
logistic_model = LogisticRegression(max_iter=1000)

# Train model
logistic_model.fit(X_train_c, y_train_c)

# Extract weights
w1 = logistic_model.coef_[0][0]
w2 = logistic_model.coef_[0][1]

# Extract bias
b = logistic_model.intercept_[0]

print("w1 =", w1)
print("w2 =", w2)
print("b  =", b)


# ==========================================
# Custom Sigmoid Function
# ==========================================

def my_sigmoid(z):
    return 1 / (1 + np.exp(-z))


# ==========================================
# Select one sample from test set
# ==========================================

sample = X_test_c.iloc[0]

X1_sample = sample['duration']
X2_sample = sample['balance']

# Calculate z manually
z = w1 * X1_sample + w2 * X2_sample + b

# Apply custom sigmoid
manual_probability = my_sigmoid(z)

# Model probability
model_probability = logistic_model.predict_proba(
    sample.to_frame().T
)[0][1]

print("\nSelected Sample:")
print(sample)

print("\nz =", z)

print("\nManual Sigmoid Probability:")
print(manual_probability)

print("\nModel predict_proba Probability:")
print(model_probability)

print("\nDo they match?")
print(np.isclose(manual_probability, model_probability))

# ==========================================
# QUESTION 5
# Model Evaluation
# ==========================================

# Predictions
y_pred_class = logistic_model.predict(X_test_c)

# Accuracy
accuracy = accuracy_score(y_test_c, y_pred_class)

print("Accuracy Score:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test_c, y_pred_class)

print("\nConfusion Matrix:")
print(cm)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test_c, y_pred_class))


# ==========================================
# Plot Confusion Matrix
# ==========================================

plt.figure(figsize=(6, 5))

plt.imshow(cm)

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")

plt.xticks([0, 1], ['0', '1'])
plt.yticks([0, 1], ['0', '1'])

for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i, j],
                 ha="center",
                 va="center")

plt.colorbar()
plt.show()

# ==========================================
# QUESTION 6
# Regression Plot
# ==========================================

plt.figure(figsize=(8, 6))

plt.scatter(
    X_test,
    y_test,
    alpha=0.6,
    label="Test Data"
)

plt.plot(
    X_test,
    y_pred,
    linewidth=2,
    label="Regression Line"
)

plt.xlabel("Age")
plt.ylabel("Balance")
plt.title("Linear Regression: Age vs Balance")

plt.legend()
plt.show()

# ==========================================
# Classification Plot
# ==========================================

plt.figure(figsize=(10, 7))

# Plot class 0
class_0 = df[df['deposit_binary'] == 0]

plt.scatter(
    class_0['duration'],
    class_0['balance'],
    label='Class 0'
)

# Plot class 1
class_1 = df[df['deposit_binary'] == 1]

plt.scatter(
    class_1['duration'],
    class_1['balance'],
    label='Class 1'
)

# Decision Boundary
x1_values = np.linspace(
    df['duration'].min(),
    df['duration'].max(),
    200
)

x2_values = -(w1 * x1_values + b) / w2

plt.plot(
    x1_values,
    x2_values,
    linewidth=2,
    label='Decision Boundary'
)

plt.xlabel("Duration")
plt.ylabel("Balance")

plt.title("Logistic Regression Classification")

plt.legend()
plt.show()